// GENERATED by scripts/gen-clock-glyphs.py — do not edit; re-run the script.
//
// Per colour platform and face: each glyph's column in its strip resource
// (resources/img/clock-<face>~<platform>.png), its ink width, its left bearing (ink
// start relative to the pen) and its advance, in pixels, for the glyphs '0'..'9' then
// ':'. The strips' height is the face's ink height, in clock_glyphs_ink.h. Included by
// src/c/layers/clock_glyphs.c only.
#pragma once

#include <pebble.h>
#include "clock_glyphs_ink.h"

#define CLOCK_GLYPH_COUNT 11

typedef struct {
    uint16_t x;    // first column in the strip
    uint8_t  w;    // ink columns
    int8_t   lsb;  // ink start, relative to the pen
    uint8_t  adv;  // pen advance
} ClockGlyph;

#if defined(PBL_PLATFORM_BASALT)
static const ClockGlyph CLOCK_GLYPHS_ROBOTO[CLOCK_GLYPH_COUNT] = {
    {   0, 24,   2, 28 },  // '0'
    {  24, 15,   4, 28 },  // '1'
    {  39, 26,   1, 28 },  // '2'
    {  65, 25,   1, 28 },  // '3'
    {  90, 26,   1, 28 },  // '4'
    { 116, 24,   2, 28 },  // '5'
    { 140, 25,   2, 28 },  // '6'
    { 165, 25,   1, 28 },  // '7'
    { 190, 24,   2, 28 },  // '8'
    { 214, 24,   2, 28 },  // '9'
    { 238,  8,   3, 14 },  // ':'
};
static const ClockGlyph CLOCK_GLYPHS_BITHAM[CLOCK_GLYPH_COUNT] = {
    {   0, 26,   2, 29 },  // '0'
    {  26, 11,   1, 16 },  // '1'
    {  37, 23,   1, 25 },  // '2'
    {  60, 23,   0, 25 },  // '3'
    {  83, 27,   2, 29 },  // '4'
    { 110, 23,   1, 25 },  // '5'
    { 133, 24,   2, 27 },  // '6'
    { 157, 23,   1, 26 },  // '7'
    { 180, 25,   2, 28 },  // '8'
    { 205, 24,   1, 27 },  // '9'
    { 229,  6,   2, 10 },  // ':'
};
#elif defined(PBL_PLATFORM_EMERY)
static const ClockGlyph CLOCK_GLYPHS_ROBOTO[CLOCK_GLYPH_COUNT] = {
    {   0, 30,   3, 36 },  // '0'
    {  30, 19,   5, 36 },  // '1'
    {  49, 31,   2, 36 },  // '2'
    {  80, 31,   2, 36 },  // '3'
    { 111, 33,   1, 36 },  // '4'
    { 144, 30,   3, 36 },  // '5'
    { 174, 31,   3, 36 },  // '6'
    { 205, 31,   2, 36 },  // '7'
    { 236, 30,   3, 36 },  // '8'
    { 266, 30,   2, 36 },  // '9'
    { 296, 11,   3, 18 },  // ':'
};
static const ClockGlyph CLOCK_GLYPHS_BITHAM[CLOCK_GLYPH_COUNT] = {
    {   0, 36,   3, 41 },  // '0'
    {  36, 16,   0, 23 },  // '1'
    {  52, 32,   1, 36 },  // '2'
    {  84, 33,   0, 35 },  // '3'
    { 117, 38,   2, 41 },  // '4'
    { 155, 33,   1, 36 },  // '5'
    { 188, 34,   3, 38 },  // '6'
    { 222, 33,   2, 37 },  // '7'
    { 255, 36,   2, 40 },  // '8'
    { 291, 35,   1, 38 },  // '9'
    { 326,  8,   3, 14 },  // ':'
};
#else
#error "No anti-aliased clock glyphs for this colour platform: add it to scripts/gen-clock-glyphs.py"
#endif
