#include "clock_glyphs.h"

#if defined(PBL_COLOR)

#include "c/appendix/config.h"      // TimeFont
#include "c/appendix/theme.h"       // theme_is_bw
#include "clock_glyphs_metrics.h"   // GENERATED by scripts/gen-clock-glyphs.py

typedef struct {
    uint32_t resource_id;     // the face's strip (resources/img/clock-<face>~<platform>.png)
    const ClockGlyph *glyphs; // '0'..'9', then ':'
    uint8_t ink_h;
} ClockGlyphFace;

static const ClockGlyphFace *face_for(int16_t time_font) {
    static const ClockGlyphFace roboto = {
        RESOURCE_ID_CLOCK_STRIP_ROBOTO, CLOCK_GLYPHS_ROBOTO, CLOCK_GLYPHS_ROBOTO_INK_H };
    static const ClockGlyphFace bitham = {
        RESOURCE_ID_CLOCK_STRIP_BITHAM, CLOCK_GLYPHS_BITHAM, CLOCK_GLYPHS_BITHAM_INK_H };
    if (time_font == TIME_FONT_ROBOTO) { return &roboto; }
    if (time_font == TIME_FONT_BITHAM) { return &bitham; }
    return NULL;
}

// The glyph for one character of the time string, or NULL for anything the strip lacks.
static const ClockGlyph *glyph_for(const ClockGlyphFace *face, char c) {
    if (c >= '0' && c <= '9') { return &face->glyphs[c - '0']; }
    if (c == ':') { return &face->glyphs[10]; }
    return NULL;
}

bool clock_glyphs_face(int16_t time_font) {
    return face_for(time_font) != NULL;
}

int16_t clock_glyphs_width(int16_t time_font, const char *text) {
    const ClockGlyphFace *face = face_for(time_font);
    int16_t w = 0;
    for (; face && *text; text++) {
        const ClockGlyph *g = glyph_for(face, *text);
        if (g) { w += g->adv; }
    }
    return w;
}

void clock_glyphs_draw(GContext *ctx, int16_t time_font, const char *text, GPoint origin,
                       GColor color) {
    const ClockGlyphFace *face = face_for(time_font);
    if (!face) { return; }
    GBitmap *strip = gbitmap_create_with_resource(face->resource_id);
    if (!strip) { return; }
    // Recolour: the strip's four palette entries are its four alpha levels (in whatever order
    // the SDK packed them), so giving every entry the clock colour's RGB and keeping its own
    // alpha turns the strip into this colour at the glyphs' coverage. GCompOpSet then blends
    // each pixel over what is already drawn at that alpha — the anti-aliasing is entirely in
    // the firmware's documented transparency path.
    //
    // Except in a B&W theme, which promises to draw exactly what a real B&W watch draws
    // (theme.h): there every alpha snaps to opaque or clear at half coverage (the generator's
    // level 2 and up), so the same strip inks in pure fg with no grey edge. On emery that also
    // drops the round digits' faint overshoot, the one row above and below the flat digits' ink.
    const bool crisp = theme_is_bw();
    GColor *palette = gbitmap_get_palette(strip);
    for (int i = 0; palette && i < 4; i++) {
        uint8_t alpha = palette[i].argb & 0xC0;
        if (crisp) { alpha = (alpha >= 0x80) ? 0xC0 : 0x00; }
        palette[i].argb = (uint8_t)(alpha | (color.argb & 0x3F));
    }
    graphics_context_set_compositing_mode(ctx, GCompOpSet);
    int16_t pen = origin.x;
    for (; *text; text++) {
        const ClockGlyph *g = glyph_for(face, *text);
        if (!g) { continue; }
        // The strip is a sprite sheet: its bounds select this glyph's columns, and the blit
        // reads from the bounds' origin.
        gbitmap_set_bounds(strip, GRect(g->x, 0, g->w, face->ink_h));
        graphics_draw_bitmap_in_rect(ctx, strip,
                                     GRect(pen + g->lsb, origin.y, g->w, face->ink_h));
        pen += g->adv;
    }
    graphics_context_set_compositing_mode(ctx, GCompOpAssign);
    gbitmap_destroy(strip);
}

#endif   /* PBL_COLOR — the B/W platforms keep the 1-bit system fonts */
