// GENERATED by scripts/gen-clock-glyphs.py — do not edit; re-run the script.
//
// Per colour platform and face: each glyph's column in its strip resource
// (resources/img/clock-<face>~<platform>.png), its ink width, its left bearing (ink
// start relative to the pen) and its advance, in pixels, for the glyphs '0'..'9' then
// ':'. The strips' height is the face's ink height, in clock_glyphs_ink.h. Included by
// src/c/layers/clock_glyphs.c only.
#pragma once

#include <pebble.h>
#include "clock_glyphs_ink.h"

#define CLOCK_GLYPH_COUNT 11

typedef struct {
    uint16_t x;    // first column in the strip
    uint8_t  w;    // ink columns
    int8_t   lsb;  // ink start, relative to the pen
    uint8_t  adv;  // pen advance
} ClockGlyph;

#if defined(PBL_PLATFORM_BASALT)
static const ClockGlyph CLOCK_GLYPHS_ROBOTO[CLOCK_GLYPH_COUNT] = {
    {   0, 24,   2, 28 },  // '0'
    {  24, 15,   4, 28 },  // '1'
    {  39, 25,   2, 28 },  // '2'
    {  64, 24,   2, 28 },  // '3'
    {  88, 26,   1, 28 },  // '4'
    { 114, 24,   2, 28 },  // '5'
    { 138, 24,   2, 28 },  // '6'
    { 162, 25,   1, 28 },  // '7'
    { 187, 24,   2, 28 },  // '8'
    { 211, 24,   2, 28 },  // '9'
    { 235,  8,   3, 14 },  // ':'
};
static const ClockGlyph CLOCK_GLYPHS_BITHAM[CLOCK_GLYPH_COUNT] = {
    {   0, 25,   2, 29 },  // '0'
    {  25, 12,   0, 16 },  // '1'
    {  37, 23,   1, 25 },  // '2'
    {  60, 22,   1, 25 },  // '3'
    {  82, 27,   2, 29 },  // '4'
    { 109, 23,   0, 25 },  // '5'
    { 132, 24,   2, 27 },  // '6'
    { 156, 23,   1, 26 },  // '7'
    { 179, 24,   2, 28 },  // '8'
    { 203, 24,   1, 27 },  // '9'
    { 227,  6,   2, 10 },  // ':'
};
#elif defined(PBL_PLATFORM_EMERY)
static const ClockGlyph CLOCK_GLYPHS_ROBOTO[CLOCK_GLYPH_COUNT] = {
    {   0, 30,   3, 36 },  // '0'
    {  30, 20,   5, 36 },  // '1'
    {  50, 31,   2, 36 },  // '2'
    {  81, 31,   2, 36 },  // '3'
    { 112, 33,   1, 36 },  // '4'
    { 145, 30,   3, 36 },  // '5'
    { 175, 30,   3, 36 },  // '6'
    { 205, 31,   2, 36 },  // '7'
    { 236, 30,   3, 36 },  // '8'
    { 266, 30,   2, 36 },  // '9'
    { 296, 10,   4, 18 },  // ':'
};
static const ClockGlyph CLOCK_GLYPHS_BITHAM[CLOCK_GLYPH_COUNT] = {
    {   0, 35,   3, 41 },  // '0'
    {  35, 16,   0, 23 },  // '1'
    {  51, 33,   0, 36 },  // '2'
    {  84, 32,   0, 35 },  // '3'
    { 116, 38,   3, 41 },  // '4'
    { 154, 32,   2, 36 },  // '5'
    { 186, 34,   3, 38 },  // '6'
    { 220, 33,   2, 37 },  // '7'
    { 253, 34,   3, 40 },  // '8'
    { 287, 33,   2, 38 },  // '9'
    { 320,  8,   3, 14 },  // ':'
};
#else
#error "No anti-aliased clock glyphs for this colour platform: add it to scripts/gen-clock-glyphs.py"
#endif
