#include "clock_glyphs.h"

#if defined(PBL_COLOR)

#include "c/appendix/config.h"      // TimeFont
#include "c/appendix/theme.h"       // theme_is_bw
#include "clock_glyphs_metrics.h"   // GENERATED by scripts/gen-clock-glyphs.py

// A face's glyph images are consecutive resources, '0'..'9' then ':' (package.template.json),
// so its first id plus a glyph's index names each one.
_Static_assert(RESOURCE_ID_CLOCK_ROBOTO_10 == RESOURCE_ID_CLOCK_ROBOTO_0 + CLOCK_GLYPH_COUNT - 1,
               "CLOCK_ROBOTO_0..10 must be consecutive resources");
_Static_assert(RESOURCE_ID_CLOCK_BITHAM_10 == RESOURCE_ID_CLOCK_BITHAM_0 + CLOCK_GLYPH_COUNT - 1,
               "CLOCK_BITHAM_0..10 must be consecutive resources");

typedef struct {
    uint32_t first_id;        // the face's '0' (resources/img/clock-<face>-0~<platform>.png)
    const ClockGlyph *glyphs; // '0'..'9', then ':'
    uint8_t ink_h;
} ClockGlyphFace;

static const ClockGlyphFace *face_for(int16_t time_font) {
    static const ClockGlyphFace roboto = {
        RESOURCE_ID_CLOCK_ROBOTO_0, CLOCK_GLYPHS_ROBOTO, CLOCK_GLYPHS_ROBOTO_INK_H };
    static const ClockGlyphFace bitham = {
        RESOURCE_ID_CLOCK_BITHAM_0, CLOCK_GLYPHS_BITHAM, CLOCK_GLYPHS_BITHAM_INK_H };
    if (time_font == TIME_FONT_ROBOTO) { return &roboto; }
    if (time_font == TIME_FONT_BITHAM) { return &bitham; }
    return NULL;
}

// The index of one character of the time string in its face ('0'..'9', then ':'), or -1 for
// anything the faces lack.
static int glyph_index(char c) {
    if (c >= '0' && c <= '9') { return c - '0'; }
    if (c == ':') { return CLOCK_GLYPH_COUNT - 1; }
    return -1;
}

bool clock_glyphs_face(int16_t time_font) {
    return face_for(time_font) != NULL;
}

int16_t clock_glyphs_width(int16_t time_font, const char *text) {
    const ClockGlyphFace *face = face_for(time_font);
    int16_t w = 0;
    for (; face && *text; text++) {
        const int i = glyph_index(*text);
        if (i >= 0) { w += face->glyphs[i].adv; }
    }
    return w;
}

void clock_glyphs_draw(GContext *ctx, int16_t time_font, const char *text, GPoint origin,
                       GColor color) {
    const ClockGlyphFace *face = face_for(time_font);
    if (!face) { return; }
    // Recolour: a glyph's palette entries are its alpha levels (in whatever order the SDK
    // packed them), so giving every entry the clock colour's RGB and keeping its own alpha
    // turns the glyph into this colour at its coverage. GCompOpSet then blends each pixel over
    // what is already drawn at that alpha — the anti-aliasing is entirely in the firmware's
    // documented transparency path.
    //
    // Except in a B&W theme, which promises to draw exactly what a real B&W watch draws
    // (theme.h): there every alpha snaps to opaque or clear at half coverage (the generator's
    // level 2 and up), so the same glyph inks in pure fg with no grey edge. On emery that also
    // drops the round digits' faint overshoot, the one row above and below the flat digits' ink.
    const bool crisp = theme_is_bw();
    graphics_context_set_compositing_mode(ctx, GCompOpSet);
    int16_t pen = origin.x;
    for (; *text; text++) {
        const int i = glyph_index(*text);
        if (i < 0) { continue; }
        const ClockGlyph *g = &face->glyphs[i];
        // One glyph at a time, freed before the next loads: the heap holds at most one glyph
        // (basalt's widest is 0.3 KB) rather than the face's whole set. A glyph that fails to
        // load is left out of this frame, its advance kept, rather than crashing.
        GBitmap *glyph = gbitmap_create_with_resource(face->first_id + (uint32_t)i);
        if (glyph) {
            // The SDK packs these images as exactly 2 bits (memoryFormat 2BitPalette, even for
            // a glyph with fewer alpha levels), so the palette has 4 entries. Any other format
            // is left as it is rather than written past its palette.
            GColor *palette = (gbitmap_get_format(glyph) == GBitmapFormat2BitPalette)
                              ? gbitmap_get_palette(glyph) : NULL;
            for (int k = 0; palette && k < 4; k++) {
                uint8_t alpha = palette[k].argb & 0xC0;
                if (crisp) { alpha = (alpha >= 0x80) ? 0xC0 : 0x00; }
                palette[k].argb = (uint8_t)(alpha | (color.argb & 0x3F));
            }
            graphics_draw_bitmap_in_rect(ctx, glyph,
                                         GRect(pen + g->lsb, origin.y, g->w, face->ink_h));
            gbitmap_destroy(glyph);
        }
        pen += g->adv;
    }
    graphics_context_set_compositing_mode(ctx, GCompOpAssign);
}

#endif   /* PBL_COLOR — the B/W platforms keep the 1-bit system fonts */
