// GENERATED by scripts/gen-clock-glyphs.py — do not edit; re-run the script.
//
// Per colour platform, each anti-aliased face's union ink height: the rows its digits
// occupy, which is also its strip's height. Read by clock_glyphs_metrics.h and by
// clock_ink.c, whose ClockInk table seats the clock band with it.
#pragma once

#if defined(PBL_PLATFORM_BASALT)
#define CLOCK_GLYPHS_ROBOTO_INK_H 34  // 49 px
#define CLOCK_GLYPHS_BITHAM_INK_H 31  // 44 px
#elif defined(PBL_PLATFORM_EMERY)
#define CLOCK_GLYPHS_ROBOTO_INK_H 46  // 62 px
#define CLOCK_GLYPHS_BITHAM_INK_H 45  // 62 px
#else
#error "No anti-aliased clock glyphs for this colour platform: add it to scripts/gen-clock-glyphs.py"
#endif
