// GENERATED by scripts/gen-clock-glyphs.py — do not edit; re-run the script.
//
// Per colour platform and face: each glyph's ink width (the width of its image,
// resources/img/clock-<face>-<n>~<platform>.png), its left bearing (ink start relative
// to the pen) and its advance, in pixels, for the glyphs '0'..'9' then ':'. The
// images' height is the face's ink height, in clock_glyphs_ink.h. Included by
// src/c/layers/clock_glyphs.c only.
#pragma once

#include <pebble.h>
#include "clock_glyphs_ink.h"

#define CLOCK_GLYPH_COUNT 11

typedef struct {
    uint8_t  w;    // ink columns
    int8_t   lsb;  // ink start, relative to the pen
    uint8_t  adv;  // pen advance
} ClockGlyph;

#if defined(PBL_PLATFORM_BASALT)
static const ClockGlyph CLOCK_GLYPHS_ROBOTO[CLOCK_GLYPH_COUNT] = {
    { 24,   2, 28 },  // '0'
    { 15,   4, 28 },  // '1'
    { 25,   2, 28 },  // '2'
    { 25,   1, 28 },  // '3'
    { 26,   1, 28 },  // '4'
    { 24,   2, 28 },  // '5'
    { 25,   2, 28 },  // '6'
    { 25,   1, 28 },  // '7'
    { 24,   2, 28 },  // '8'
    { 24,   2, 28 },  // '9'
    {  8,   3, 14 },  // ':'
};
static const ClockGlyph CLOCK_GLYPHS_BITHAM[CLOCK_GLYPH_COUNT] = {
    { 26,   2, 29 },  // '0'
    { 11,   1, 16 },  // '1'
    { 23,   1, 25 },  // '2'
    { 23,   1, 25 },  // '3'
    { 27,   2, 29 },  // '4'
    { 23,   1, 25 },  // '5'
    { 24,   2, 27 },  // '6'
    { 23,   1, 26 },  // '7'
    { 25,   2, 28 },  // '8'
    { 25,   1, 27 },  // '9'
    {  6,   2, 10 },  // ':'
};
#elif defined(PBL_PLATFORM_EMERY)
static const ClockGlyph CLOCK_GLYPHS_ROBOTO[CLOCK_GLYPH_COUNT] = {
    { 30,   3, 36 },  // '0'
    { 19,   5, 36 },  // '1'
    { 31,   2, 36 },  // '2'
    { 31,   2, 36 },  // '3'
    { 33,   1, 36 },  // '4'
    { 31,   3, 36 },  // '5'
    { 31,   3, 36 },  // '6'
    { 31,   2, 36 },  // '7'
    { 30,   3, 36 },  // '8'
    { 30,   2, 36 },  // '9'
    { 11,   3, 18 },  // ':'
};
static const ClockGlyph CLOCK_GLYPHS_BITHAM[CLOCK_GLYPH_COUNT] = {
    { 36,   3, 41 },  // '0'
    { 16,   0, 23 },  // '1'
    { 32,   1, 36 },  // '2'
    { 33,   0, 35 },  // '3'
    { 38,   2, 41 },  // '4'
    { 33,   1, 36 },  // '5'
    { 34,   3, 38 },  // '6'
    { 33,   2, 37 },  // '7'
    { 36,   2, 40 },  // '8'
    { 35,   1, 38 },  // '9'
    {  8,   3, 14 },  // ':'
};
#else
#error "No anti-aliased clock glyphs for this colour platform: add it to scripts/gen-clock-glyphs.py"
#endif
