#include <string.h>

#include "app_message.h"
#include "config_wire.h"
#include "persist.h"
#include "palette.h"
#include "c/layers/forecast_layer.h"
#include "c/layers/weather_status_layer.h"
#include "c/layers/loading_layer.h"
#include "c/layers/rain_radar_layer.h"
#include "c/layers/calendar_layer.h"
#include "c/layers/top_status_layer.h"
#include "c/layers/health_status_layer.h"
#include "c/windows/main_window.h"
#include "c/services/watch_services.h"
#include "rain_countdown.h"
#include "memory_log.h"
#include "status_line.h"

// Payloads arrive split into categories that map onto screen areas (forecast
// chart, status row, radar). Each category is processed independently and the
// persist setters report real changes, so only the affected layers redraw.

typedef struct {
    SeriesId id;
    uint32_t trend_key;     // MESSAGE_KEY_* (values unchanged)
    uint32_t color_key;     // 0 = no per-series single-color tuple
} SeriesWire;

static bool handle_forecast(DictionaryIterator *iterator, bool *forecast_dirty) {
    Tuple *temp_trend_tuple = dict_find(iterator, MESSAGE_KEY_TEMP_TREND_UINT8);
    Tuple *forecast_start_tuple = dict_find(iterator, MESSAGE_KEY_FORECAST_START);
    Tuple *num_entries_tuple = dict_find(iterator, MESSAGE_KEY_NUM_ENTRIES);
    // Render-ready, already-selected series + line styling (PKJS owns the choice).
    Tuple *fill_color_tuple = dict_find(iterator, MESSAGE_KEY_SECONDARY_LINE_FILL_COLOR);
    Tuple *line_fill_tuple  = dict_find(iterator, MESSAGE_KEY_SECONDARY_LINE_FILL);
    Tuple *temp_min_tuple = dict_find(iterator, MESSAGE_KEY_TEMP_MIN);
    Tuple *temp_max_tuple = dict_find(iterator, MESSAGE_KEY_TEMP_MAX);

    if (!(temp_trend_tuple && forecast_start_tuple && num_entries_tuple)) {
        if (temp_trend_tuple || forecast_start_tuple || num_entries_tuple) {
            APP_LOG(APP_LOG_LEVEL_WARNING,
                    "Forecast payload incomplete (temp=%d start=%d entries=%d) — skipping",
                    temp_trend_tuple != NULL,
                    forecast_start_tuple != NULL,
                    num_entries_tuple != NULL);
        }
        return false;
    }

    // NUM_ENTRIES rides a separate tuple from the trend bytes; clamp it to the
    // trend tuple's own length so a skewed count can never size a read past
    // the array (write_data_if_changed memcmp/writes exactly this many bytes).
    int num_entries = (int) num_entries_tuple->value->int32;
    if (num_entries < 0) { num_entries = 0; }
    if (num_entries > (int) temp_trend_tuple->length) {
        num_entries = (int) temp_trend_tuple->length;
    }
#ifdef WW_ENABLE_MEMORY_LOGGING
    APP_LOG(APP_LOG_LEVEL_DEBUG, "MEM|forecast_payload|entries=%d|free=%lu|used=%lu",
            num_entries,
            (unsigned long)heap_bytes_free(),
            (unsigned long)heap_bytes_used());
#endif
    bool changed = false;
    changed |= persist_set_forecast_start((time_t) forecast_start_tuple->value->int32);
    changed |= persist_set_num_entries(num_entries);
    changed |= persist_set_temp_trend((uint8_t*) temp_trend_tuple->value->data, num_entries);
    if (temp_min_tuple) { changed |= persist_set_temp_min((int) temp_min_tuple->value->int32); }
    if (temp_max_tuple) { changed |= persist_set_temp_max((int) temp_max_tuple->value->int32); }

    // MESSAGE_KEY_* are uint32_t globals (generated by the SDK), not
    // compile-time constants, so the table must be initialized at runtime.
    const SeriesWire WIRE[] = {
        { SERIES_SECOND, MESSAGE_KEY_SECONDARY_LINE_TREND_UINT8, MESSAGE_KEY_SECONDARY_LINE_COLOR },
        { SERIES_THIRD,  MESSAGE_KEY_THIRD_LINE_TREND_UINT8,     MESSAGE_KEY_THIRD_LINE_COLOR     },
        { SERIES_BARS,   MESSAGE_KEY_BAR_TREND_UINT8,            0 },
    };
    // Render-ready series (trend + optional single color) — table-driven.
    // Element count = byte length (1 byte/elem). Empty/missing => count 0,
    // which the per-series setter treats per its own semantics (line/bar keep
    // a 0 count + stale trend; third deletes its key).
    for (unsigned w = 0; w < sizeof(WIRE) / sizeof(WIRE[0]); ++w) {
        Tuple *tt = dict_find(iterator, WIRE[w].trend_key);
        int count = tt ? (int) tt->length : 0;
        changed |= persist_series_set_trend(WIRE[w].id,
                       count ? (uint8_t*) tt->value->data : NULL, count);
        if (WIRE[w].color_key) {
            Tuple *ct = dict_find(iterator, WIRE[w].color_key);
            if (ct) {
                changed |= persist_series_set_color(WIRE[w].id,
                               GColorFromHEX(ct->value->int32));
            }
        }
    }
    // SECOND area-fill extras stay explicit (no generic single-color slot).
    if (fill_color_tuple) {
        changed |= persist_set_fill_color(GColorFromHEX(fill_color_tuple->value->int32));
    }
    if (line_fill_tuple) {
        changed |= persist_set_line_fill((bool)(line_fill_tuple->value->int16));
    }

    *forecast_dirty |= changed;
    return true;
}

static bool handle_status(DictionaryIterator *iterator, bool *status_dirty, bool *radar_dirty) {
    Tuple *is_sleeping_tuple = dict_find(iterator, MESSAGE_KEY_IS_SLEEPING);

    if (!is_sleeping_tuple) {
        return false;
    }

    bool changed = false;
    const bool sleeping = (bool) is_sleeping_tuple->value->int16;
    changed |= persist_set_is_sleeping(sleeping);
    if (sleeping) {
        // Sleep onset latches the radar area into snooze immediately.
        // The latch is released on the wake transition by the awake check
        // in inbox_received_callback.
        *radar_dirty |= persist_set_radar_snooze(true);
    }

    *status_dirty |= changed;
    return true;
}

static uint32_t status_line_key(int line_id) {
    switch (line_id) {
        case 0: return MESSAGE_KEY_STATUS_LINE_1_UINT8;
        case 1: return MESSAGE_KEY_STATUS_LINE_2_UINT8;
        case 2: return MESSAGE_KEY_STATUS_LINE_3_UINT8;
        default: return MESSAGE_KEY_STATUS_LINE_4_UINT8;
    }
}

static bool handle_status_lines(DictionaryIterator *iterator, bool *status_dirty) {
    bool any = false;
    bool changed = false;
    for (int i = 0; i < STATUS_LINE_COUNT; i++) {
        Tuple *tuple = dict_find(iterator, status_line_key(i));
        if (!tuple) { continue; }
        any = true;
        if (tuple->type != TUPLE_BYTE_ARRAY ||
            !status_line_validate(tuple->value->data, tuple->length)) {
            // Reject atomically; the last good persisted line stays intact.
            APP_LOG(APP_LOG_LEVEL_WARNING,
                    "Status line %d invalid (%u bytes) — skipping", i + 1,
                    (unsigned) tuple->length);
            continue;
        }
        changed |= persist_set_status_line((uint8_t) i, tuple->value->data,
                                           tuple->length);
    }
    *status_dirty |= changed;
    return any;
}

static bool handle_notice(DictionaryIterator *iterator, bool *notice_dirty) {
    Tuple *notice_tuple = dict_find(iterator, MESSAGE_KEY_NOTICE_TEXT);
    if (!notice_tuple) {
        return false;
    }
    // A CSTRING tuple; an empty string clears the overlay.
    const char *text = (notice_tuple->type == TUPLE_CSTRING)
        ? notice_tuple->value->cstring : "";
    *notice_dirty |= persist_set_notice_text(text);
    return true;
}

static bool handle_sun_events(DictionaryIterator *iterator, bool *forecast_dirty, bool *status_dirty) {
    Tuple *sun_events_tuple = dict_find(iterator, MESSAGE_KEY_SUN_EVENTS);
    if (!sun_events_tuple) {
        return false;
    }

    // Packed as one start-type byte followed by two epoch timestamps; a
    // shorter tuple is corrupt/skewed — don't read past its end.
    if (sun_events_tuple->length < (int) (1 + 2 * sizeof(time_t))) {
        return false;
    }
    uint8_t sun_event_start_type = (uint8_t) sun_events_tuple->value->uint8;
    time_t *sun_event_times = (time_t*) (sun_events_tuple->value->data + 1);
    bool changed = false;
    changed |= persist_set_sun_event_start_type(sun_event_start_type);
    changed |= persist_set_sun_event_times(sun_event_times, 2);

    // Sun events feed the chart's day/night shading and the status row.
    *forecast_dirty |= changed;
    *status_dirty |= changed;
    return true;
}

#if defined(WW_RAIN_RADAR)
static bool handle_rain_radar(DictionaryIterator *iterator, bool *radar_dirty) {
    Tuple *rain_radar_exact_tuple = dict_find(iterator, MESSAGE_KEY_RAIN_RADAR_TREND_UINT8);
    Tuple *rain_radar_area_tuple  = dict_find(iterator, MESSAGE_KEY_RAIN_RADAR_TREND_AREA_UINT8);
    Tuple *rain_radar_start_tuple = dict_find(iterator, MESSAGE_KEY_RAIN_RADAR_START);

    if (!(rain_radar_exact_tuple && rain_radar_area_tuple && rain_radar_start_tuple)) {
        if (rain_radar_exact_tuple || rain_radar_area_tuple) {
            // Partial radar payload — log and discard so persist never holds half-state.
            // RAIN_RADAR_START alone is too generic an int32 to count as radar-flavoured.
            APP_LOG(APP_LOG_LEVEL_WARNING,
                    "Rain-radar payload incomplete (exact=%d area=%d start=%d) — skipping",
                    rain_radar_exact_tuple != NULL,
                    rain_radar_area_tuple  != NULL,
                    rain_radar_start_tuple != NULL);
            return true;
        }
        return false;
    }

    bool changed = false;
    if (rain_radar_exact_tuple->length == 0) {
        // Empty array from a non-DWD provider — clear persisted radar data.
        uint8_t zeros[24] = {0};
        changed |= persist_set_rain_radar_trend(zeros, 24);
        changed |= persist_set_rain_radar_trend_area(zeros, 24);
        changed |= persist_set_rain_radar_start(0);
    } else if (rain_radar_exact_tuple->length < 24 || rain_radar_area_tuple->length < 24) {
        // Short arrays (version skew / corrupt payload) — discard rather than
        // overread the inbox and persist the trailing bytes as intensities.
        APP_LOG(APP_LOG_LEVEL_WARNING,
                "Rain-radar arrays too short (exact=%u area=%u) — skipping",
                (unsigned) rain_radar_exact_tuple->length,
                (unsigned) rain_radar_area_tuple->length);
    } else {
        changed |= persist_set_rain_radar_trend(
            (uint8_t*) rain_radar_exact_tuple->value->data, 24);
        changed |= persist_set_rain_radar_trend_area(
            (uint8_t*) rain_radar_area_tuple->value->data, 24);
        changed |= persist_set_rain_radar_start(
            (time_t) rain_radar_start_tuple->value->int32);
    }
    *radar_dirty |= changed;
    return true;
}
#endif  // WW_RAIN_RADAR

static bool handle_palette(DictionaryIterator *iterator, bool *forecast_dirty,
                           bool *radar_dirty) {
    Tuple *bar_tuple   = dict_find(iterator, MESSAGE_KEY_BAR_PALETTE_UINT8);
#if defined(WW_RAIN_RADAR)
    Tuple *radar_tuple = dict_find(iterator, MESSAGE_KEY_RADAR_PALETTE_UINT8);
    if (!bar_tuple && !radar_tuple) {
        return false;
    }
#else
    // aplite: no radar layer, so the radar palette is never applied.
    (void) radar_dirty;
    if (!bar_tuple) {
        return false;
    }
#endif
    if (bar_tuple) {
        *forecast_dirty |= palette_set_bar(bar_tuple->value->data, (int) bar_tuple->length);
    }
#if defined(WW_RAIN_RADAR)
    if (radar_tuple) {
        *radar_dirty |= palette_set_radar(radar_tuple->value->data, (int) radar_tuple->length);
    }
#endif
    return true;
}

// Parse (bytes→Config, config_wire.c) is separate from apply (Config→persist +
// cache reload + dirty bit, here). config_parse_wire returning false means the
// message carries no config — normal for weather messages.
static bool handle_clay_config(DictionaryIterator *iterator, bool *config_dirty) {
    Config config;
    if (!config_parse_wire(iterator, &config)) {
        return false;
    }
    if (persist_set_config(config)) {
        config_refresh();   // reload the cached config (persist no longer does this)
        *config_dirty = true;
    }
    return true;
}

static bool handle_holidays(DictionaryIterator *iterator, bool *calendar_dirty) {
    Tuple *holidays_tuple = dict_find(iterator, MESSAGE_KEY_HOLIDAYS);
    if (!holidays_tuple || holidays_tuple->length < 8) {
        return false;
    }

    // Packed little-endian: bytes 0-3 = int32 anchor (serial day of bit 0's
    // date), bytes 4-7 = uint32 mask (bit j => date anchor+j is a holiday).
    const uint8_t *d = holidays_tuple->value->data;
    int32_t anchor = (int32_t) ((uint32_t) d[0]
        | ((uint32_t) d[1] << 8)
        | ((uint32_t) d[2] << 16)
        | ((uint32_t) d[3] << 24));
    uint32_t mask = (uint32_t) d[4]
        | ((uint32_t) d[5] << 8)
        | ((uint32_t) d[6] << 16)
        | ((uint32_t) d[7] << 24);

    bool changed = false;
    changed |= persist_set_holiday_anchor(anchor);
    changed |= persist_set_holiday_mask(mask);
    *calendar_dirty |= changed;
    return true;
}

static void inbox_received_callback(DictionaryIterator *iterator, void *context) {
    APP_LOG(APP_LOG_LEVEL_DEBUG, "Inbox received: %u bytes",
            (unsigned) dict_size(iterator));

    bool handled = false;
    bool forecast_dirty = false;  // chart + loading overlay
    bool notice_dirty = false;    // fetch-error / info overlay text
    bool status_dirty = false;    // status row
    bool radar_dirty = false;     // radar chart + top-view availability
    bool config_dirty = false;    // whole window (config feeds every layer)
    bool calendar_dirty = false;  // calendar holiday highlights only
    bool forecast_present = handle_forecast(iterator, &forecast_dirty);
    handled |= forecast_present;
    handled |= handle_notice(iterator, &notice_dirty);
    // A forecast only ever arrives from a successful fetch, so any forecast
    // payload clears a lingering error/info overlay (self-heal if a phone→watch
    // clear was ever missed).
    if (forecast_present) {
        notice_dirty |= persist_set_notice_text("");
    }
    handled |= handle_status(iterator, &status_dirty, &radar_dirty);
    handled |= handle_status_lines(iterator, &status_dirty);
    handled |= handle_sun_events(iterator, &forecast_dirty, &status_dirty);
#if defined(WW_RAIN_RADAR)
    // aplite has no radar layer (--gc-sections reaps rain_radar_layer.c), so it
    // ignores inbound radar payloads; the whole radar persist surface drops too.
    handled |= handle_rain_radar(iterator, &radar_dirty);
#endif
    handled |= handle_palette(iterator, &forecast_dirty, &radar_dirty);
    handled |= handle_clay_config(iterator, &config_dirty);
    handled |= handle_holidays(iterator, &calendar_dirty);

    // Release the radar-snooze latch whenever we're awake. Runs after every
    // handler so it can't race the IS_SLEEPING tuple in the same payload.
    // persist_set_radar_snooze is idempotent, so this only does work on the
    // actual wake transition. The latch must NOT be gated on a fresh radar
    // payload: the outbox dedupes the radar category independently, so when
    // the post-wake radar is a dry, merely time-shifted window it is
    // suppressed (overlap matches + tail dry) and no releasing payload ever
    // arrives — which used to leave the snooze screen latched forever. The
    // cached chart is safe to reveal regardless: rain_radar_layer_tick
    // self-advances the window every minute during sleep, so it already
    // holds exactly the data PKJS would (re)send.
    if (!persist_get_is_sleeping()) {
        radar_dirty |= persist_set_radar_snooze(false);
    }

    if (config_dirty) {
        main_window_apply_theme();
        main_window_relayout();
        main_window_refresh();
        // health_mode may have been changed (e.g. to off) while the alternate view is
        // shown; re-apply the view so the watch falls back to forecast immediately.
        main_window_apply_top_view();
    }
    if (forecast_dirty || notice_dirty) {
        loading_layer_refresh();
    }
    if (forecast_dirty) {
        forecast_layer_refresh();
    }
    if (status_dirty) {
        weather_status_layer_refresh();
        top_status_layer_refresh();
#if defined(PBL_HEALTH)
        health_status_layer_refresh();
#endif
    }
    if (radar_dirty) {
#if defined(WW_RAIN_RADAR)
        rain_radar_layer_refresh();
#endif
        // The radar payload (or the snooze latch/release) is the rain-countdown's
        // only data-change source: rescan the cache, then repaint the strip.
        // aplite drops the rain-countdown alert (24 KB budget), so it skips the
        // rescan and rain_countdown.c is --gc-sections'd out of that image.
#ifndef PBL_PLATFORM_APLITE
        rain_countdown_refresh(watch_services_now());
#endif
        top_status_layer_refresh();
        // Radar availability may have switched — re-evaluate the top view so
        // a cleared radar falls back to the calendar.
        main_window_apply_top_view();
    }
    if (calendar_dirty && !config_dirty) {
        calendar_layer_refresh();
    }
    if (!handled) {
        APP_LOG(APP_LOG_LEVEL_WARNING, "Bad payload received in app_message.c");
    }
}

static void inbox_dropped_callback(AppMessageResult reason, void *context) {
    APP_LOG(APP_LOG_LEVEL_ERROR, "Message dropped!");
}

void app_message_send_startup_state(bool has_forecast_data) {
    DictionaryIterator *outbox;
    AppMessageResult result = app_message_outbox_begin(&outbox);

    if (result != APP_MSG_OK) {
        APP_LOG(APP_LOG_LEVEL_ERROR, "Unable to begin startup outbox: %d", result);
        return;
    }

    dict_write_uint8(outbox, MESSAGE_KEY_WATCH_HAS_FORECAST_DATA, has_forecast_data ? 1 : 0);
    dict_write_uint8(outbox, MESSAGE_KEY_WATCH_HAS_CONFIG, persist_has_config() ? 1 : 0);
    result = app_message_outbox_send();

    if (result != APP_MSG_OK) {
        APP_LOG(APP_LOG_LEVEL_ERROR, "Unable to send startup state: %d", result);
    }
}

void app_message_init() {
    app_message_register_inbox_received(inbox_received_callback);
    app_message_register_inbox_dropped(inbox_dropped_callback);

    // All changed categories ride in one inbound message (outbox.js bundles
    // them because the channel is half-duplex). The heaviest bundle is DWD +
    // wind: the third line (any metric, including gust) rides alongside the
    // secondary line + THIRD_LINE_COLOR, plus rain radar + status + sun.
    // The palette now rides the Clay message instead (see clay-payload.js).
    // test/inbox-size.test.js is the authoritative computation.
    // 528 (was 512): the selectable top-strip middle slot lets City pack up to
    // 19 text bytes where the fixed Date packed none (+19 B worst case, 517 B).
    const int inbox_size = 528;
    const int outbox_size = dict_calc_buffer_size(2, sizeof(uint8_t), sizeof(uint8_t));
    APP_LOG(APP_LOG_LEVEL_INFO, "AppMessage buffer sizes: inbox=%d outbox=%d", inbox_size, outbox_size);
    app_message_open(inbox_size, outbox_size);
    MEMORY_LOG_HEAP("after_app_message_open");
}
