create type public.weather_provider as enum ('wunderground', 'openweathermap', 'mock', 'dwd', 'openmeteo', 'metno', 'yandex', 'tomorrowio');

create table public.telemetry_weather_fetch (
  id bigint generated by default as identity primary key,
  received_at timestamp with time zone not null default now(),
  -- When the row physically arrived (vs received_at = when the EVENT happened,
  -- client-stamped for batched events, up to 72 h earlier). The hourly rate
  -- limit counts by THIS column: batched rows carry historical received_at and
  -- would slide past a received_at-based window, making the limit void for
  -- back-dated floods. Everything analytical (DAU, prune, dashboards) keeps
  -- reading received_at.
  inserted_at timestamp with time zone not null default now(),
  account_token_hash text not null,
  watch_token_hash text,
  provider public.weather_provider not null,
  success boolean not null,
  error text,
  country_code text,
  settings_json jsonb not null default '{}'::jsonb,
  app_version text not null,
  build_profile text not null,
  watch_info jsonb not null default '{}'::jsonb, -- https://developer.repebble.com/docs/pebblekit-js/Pebble/#WatchInfo
  used_gps_cache boolean not null default false,
  gps_error_code integer,
  location_mode text,
  duration_ms integer check (duration_ms >= 0),
  attempt integer check (attempt >= 1),
  
  check ((success = true and error is null) or (success = false and error is not null and length(btrim(error)) > 0)),
  check (location_mode is null or location_mode in ('gps', 'manual_coordinates', 'manual_address')),
  check (jsonb_typeof(settings_json) = 'object'),
  check (jsonb_typeof(watch_info) = 'object')
);

alter table public.telemetry_weather_fetch enable row level security;

create policy no_api_access_telemetry_weather_fetch
on public.telemetry_weather_fetch
for all
to anon, authenticated
using (false)
with check (false);

create index telemetry_weather_fetch_account_hour_idx
  on public.telemetry_weather_fetch (account_token_hash, received_at);

-- The rate-check probe (account, inserted_at >= now()-1h) — the received_at
-- twin above keeps serving the analytical queries.
create index telemetry_weather_fetch_account_inserted_idx
  on public.telemetry_weather_fetch (account_token_hash, inserted_at);

create index telemetry_weather_fetch_dau_idx
  on public.telemetry_weather_fetch ((((received_at at time zone 'UTC'::text))::date), account_token_hash);

-- ── RPC for the telemetry-ingest edge function ──────────────────────────────
-- The API gateway logs the full URL of every PostgREST request, so the
-- per-account rate check must not ride a query filter
-- (HEAD ?account_token_hash=eq.…&inserted_at=gte.…). It goes through this
-- function instead: called as a plain POST /rest/v1/rpc/<fn>, its arguments
-- travel in the request body. SECURITY INVOKER (the default; the edge function
-- calls it with the service role, which bypasses the deny-all RLS above), an
-- empty search_path, and revoked from public/anon/authenticated below.
--
-- The caller's rows that ARRIVED since p_since: inserted_at, not received_at,
-- because batched rows carry a client-stamped received_at up to 72 h old and
-- would slide past an event-time window. Served by
-- telemetry_weather_fetch_account_inserted_idx.
create or replace function public.telemetry_recent_insert_count(
  p_account_token_hash text,
  p_since timestamp with time zone
)
returns integer
language sql
stable
set search_path = ''
as $$
  select count(*)::integer
    from public.telemetry_weather_fetch t
   where t.account_token_hash = p_account_token_hash
     and t.inserted_at >= p_since;
$$;

-- Service-role only: the telemetry-ingest edge function is the sole caller.
revoke all on function public.telemetry_recent_insert_count(text, timestamp with time zone)
  from public, anon, authenticated;
