-- Analytics rollup tables for telemetry. Declarative source of truth.
-- Never hand-write supabase/migrations/ — generate with:
--   supabase db diff -f telemetry_retention
-- Populated daily by public.telemetry_rollup_and_prune() (scheduled via
-- pg_cron in a hand-written migration). Unit of analysis is the WATCH:
-- watch_key = coalesce(watch_token_hash, account_token_hash).

-- Current snapshot: one row per watch, no history.
create table public.telemetry_watch (
  watch_key text primary key,
  account_token_hash text,
  first_seen timestamptz not null,
  last_seen timestamptz not null,
  lifetime_events integer not null default 0,
  first_app_version text,
  last_app_version text,
  country_code text,
  provider public.weather_provider,
  radar_provider text,
  watch_platform text,
  watch_model text,
  watch_language text,
  watch_firmware text,
  build_profile text,
  settings_json jsonb
);

alter table public.telemetry_watch enable row level security;

create policy no_api_access_telemetry_watch
on public.telemetry_watch
for all to anon, authenticated
using (false) with check (false);

create index telemetry_watch_last_seen_idx on public.telemetry_watch (last_seen);
create index telemetry_watch_first_seen_idx on public.telemetry_watch (first_seen);
create index telemetry_watch_last_app_version_idx on public.telemetry_watch (last_app_version);

-- Daily per-watch activity fact: one row per (watch, day).
create table public.telemetry_dau (
  watch_key text not null,
  activity_date date not null,
  account_token_hash text,
  fetch_count integer not null default 0,
  provider public.weather_provider,
  radar_provider text,
  country_code text,
  watch_platform text,
  watch_model text,
  watch_language text,
  app_version text,
  build_profile text,
  primary key (watch_key, activity_date)
);

alter table public.telemetry_dau enable row level security;

create policy no_api_access_telemetry_dau
on public.telemetry_dau
for all to anon, authenticated
using (false) with check (false);

create index telemetry_dau_activity_date_idx on public.telemetry_dau (activity_date);

-- Slim error log: one row per failed fetch (no settings_json blob).
create table public.telemetry_errors (
  id bigint generated by default as identity primary key,
  received_at timestamptz not null,
  watch_key text,
  account_token_hash text,
  provider public.weather_provider,
  error text,
  country_code text,
  app_version text,
  build_profile text,
  gps_error_code integer,
  location_mode text,
  duration_ms integer,
  attempt integer,
  watch_platform text
);

alter table public.telemetry_errors enable row level security;

create policy no_api_access_telemetry_errors
on public.telemetry_errors
for all to anon, authenticated
using (false) with check (false);

create index telemetry_errors_received_at_idx on public.telemetry_errors (received_at);
create index telemetry_errors_provider_idx on public.telemetry_errors (provider, received_at);
