// src/pkjs/settings/holiday-data.js — ES5, PKJS-parsed. Option data for the holiday
// country/region selectors in schema.js. Country values are ISO-3166-1 alpha-2 (UK = GB);
// the full set Nager.Date supports, None first then Germany (the default), then alphabetical.
// Region values are ISO-3166-2; only countries whose holidays vary by subdivision appear here.

// [label, value] pairs. None first, Germany second (default), then alphabetical.
var COUNTRY_OPTIONS = [
  ['None', 'none'],
  ['Germany', 'DE'],
  ['Albania', 'AL'],
  ['Andorra', 'AD'],
  ['Angola', 'AO'],
  ['Anguilla', 'AI'],
  ['Antigua and Barbuda', 'AG'],
  ['Argentina', 'AR'],
  ['Armenia', 'AM'],
  ['Aruba', 'AW'],
  ['Australia', 'AU'],
  ['Austria', 'AT'],
  ['Bahamas', 'BS'],
  ['Bangladesh', 'BD'],
  ['Barbados', 'BB'],
  ['Belarus', 'BY'],
  ['Belgium', 'BE'],
  ['Belize', 'BZ'],
  ['Benin', 'BJ'],
  ['Bermuda', 'BM'],
  ['Bolivia', 'BO'],
  ['Bosnia and Herzegovina', 'BA'],
  ['Botswana', 'BW'],
  ['Brazil', 'BR'],
  ['British Virgin Islands', 'VG'],
  ['Bulgaria', 'BG'],
  ['Cambodia', 'KH'],
  ['Canada', 'CA'],
  ['Caribbean Netherlands', 'BQ'],
  ['Cayman Islands', 'KY'],
  ['Chile', 'CL'],
  ['China', 'CN'],
  ['Colombia', 'CO'],
  ['Congo', 'CG'],
  ['Costa Rica', 'CR'],
  ['Croatia', 'HR'],
  ['Cuba', 'CU'],
  ['Curaçao', 'CW'],
  ['Cyprus', 'CY'],
  ['Czechia', 'CZ'],
  ['DR Congo', 'CD'],
  ['Denmark', 'DK'],
  ['Dominica', 'DM'],
  ['Dominican Republic', 'DO'],
  ['Ecuador', 'EC'],
  ['Egypt', 'EG'],
  ['El Salvador', 'SV'],
  ['Estonia', 'EE'],
  ['Falkland Islands', 'FK'],
  ['Faroe Islands', 'FO'],
  ['Finland', 'FI'],
  ['France', 'FR'],
  ['French Guiana', 'GF'],
  ['Gabon', 'GA'],
  ['Gambia', 'GM'],
  ['Georgia', 'GE'],
  ['Ghana', 'GH'],
  ['Gibraltar', 'GI'],
  ['Greece', 'GR'],
  ['Greenland', 'GL'],
  ['Grenada', 'GD'],
  ['Guadeloupe', 'GP'],
  ['Guatemala', 'GT'],
  ['Guernsey', 'GG'],
  ['Guyana', 'GY'],
  ['Haiti', 'HT'],
  ['Honduras', 'HN'],
  ['Hong Kong', 'HK'],
  ['Hungary', 'HU'],
  ['Iceland', 'IS'],
  ['Indonesia', 'ID'],
  ['Ireland', 'IE'],
  ['Isle of Man', 'IM'],
  ['Italy', 'IT'],
  ['Jamaica', 'JM'],
  ['Japan', 'JP'],
  ['Jersey', 'JE'],
  ['Kazakhstan', 'KZ'],
  ['Kenya', 'KE'],
  ['Latvia', 'LV'],
  ['Lesotho', 'LS'],
  ['Liechtenstein', 'LI'],
  ['Lithuania', 'LT'],
  ['Luxembourg', 'LU'],
  ['Madagascar', 'MG'],
  ['Malta', 'MT'],
  ['Martinique', 'MQ'],
  ['Mexico', 'MX'],
  ['Moldova', 'MD'],
  ['Monaco', 'MC'],
  ['Mongolia', 'MN'],
  ['Montenegro', 'ME'],
  ['Montserrat', 'MS'],
  ['Morocco', 'MA'],
  ['Mozambique', 'MZ'],
  ['Namibia', 'NA'],
  ['Netherlands', 'NL'],
  ['New Zealand', 'NZ'],
  ['Nicaragua', 'NI'],
  ['Niger', 'NE'],
  ['Nigeria', 'NG'],
  ['Niue', 'NU'],
  ['North Macedonia', 'MK'],
  ['Norway', 'NO'],
  ['Palau', 'PW'],
  ['Panama', 'PA'],
  ['Papua New Guinea', 'PG'],
  ['Paraguay', 'PY'],
  ['Peru', 'PE'],
  ['Philippines', 'PH'],
  ['Pitcairn Islands', 'PN'],
  ['Poland', 'PL'],
  ['Portugal', 'PT'],
  ['Puerto Rico', 'PR'],
  ['Romania', 'RO'],
  ['Russia', 'RU'],
  ['Saint Barthélemy', 'BL'],
  ['Saint Kitts and Nevis', 'KN'],
  ['Saint Lucia', 'LC'],
  ['Saint Martin', 'MF'],
  ['Saint Pierre and Miquelon', 'PM'],
  ['Saint Vincent and the Grenadines', 'VC'],
  ['Samoa', 'WS'],
  ['San Marino', 'SM'],
  ['Serbia', 'RS'],
  ['Seychelles', 'SC'],
  ['Singapore', 'SG'],
  ['Sint Maarten', 'SX'],
  ['Slovakia', 'SK'],
  ['Slovenia', 'SI'],
  ['South Africa', 'ZA'],
  ['South Korea', 'KR'],
  ['Spain', 'ES'],
  ['Suriname', 'SR'],
  ['Svalbard and Jan Mayen', 'SJ'],
  ['Sweden', 'SE'],
  ['Switzerland', 'CH'],
  ['Trinidad and Tobago', 'TT'],
  ['Tunisia', 'TN'],
  ['Turks and Caicos Islands', 'TC'],
  ['Tuvalu', 'TV'],
  ['Türkiye', 'TR'],
  ['Uganda', 'UG'],
  ['Ukraine', 'UA'],
  ['United Kingdom', 'GB'],
  ['United States', 'US'],
  ['Uruguay', 'UY'],
  ['Vatican City', 'VA'],
  ['Venezuela', 'VE'],
  ['Vietnam', 'VN'],
  ['Zimbabwe', 'ZW'],
  ['Åland Islands', 'AX']
];

// Region sub-selector options, keyed by country code. First entry is always the
// nationwide sentinel ['Whole country', 'all']; the rest are ISO-3166-2 subdivisions.
var REGION_OPTIONS = {
  DE: [
    ['Whole country', 'all'],
    ['Baden-Württemberg', 'DE-BW'],
    ['Bavaria', 'DE-BY'],
    ['Berlin', 'DE-BE'],
    ['Brandenburg', 'DE-BB'],
    ['Bremen', 'DE-HB'],
    ['Hamburg', 'DE-HH'],
    ['Hesse', 'DE-HE'],
    ['Mecklenburg-Vorpommern', 'DE-MV'],
    ['Lower Saxony', 'DE-NI'],
    ['North Rhine-Westphalia', 'DE-NW'],
    ['Rhineland-Palatinate', 'DE-RP'],
    ['Saarland', 'DE-SL'],
    ['Saxony', 'DE-SN'],
    ['Saxony-Anhalt', 'DE-ST'],
    ['Schleswig-Holstein', 'DE-SH'],
    ['Thuringia', 'DE-TH']
  ],
  // Austria's ISO-3166-2 subdivisions are numeric (AT-1..AT-9), unlike the alpha
  // suffixes elsewhere — the future watch-side holiday consumer must not assume a
  // uniform suffix shape across countries.
  AT: [
    ['Whole country', 'all'],
    ['Burgenland', 'AT-1'],
    ['Carinthia', 'AT-2'],
    ['Lower Austria', 'AT-3'],
    ['Upper Austria', 'AT-4'],
    ['Salzburg', 'AT-5'],
    ['Styria', 'AT-6'],
    ['Tyrol', 'AT-7'],
    ['Vorarlberg', 'AT-8'],
    ['Vienna', 'AT-9']
  ],
  CH: [
    ['Whole country', 'all'],
    ['Zürich', 'CH-ZH'],
    ['Bern', 'CH-BE'],
    ['Lucerne', 'CH-LU'],
    ['Uri', 'CH-UR'],
    ['Schwyz', 'CH-SZ'],
    ['Obwalden', 'CH-OW'],
    ['Nidwalden', 'CH-NW'],
    ['Glarus', 'CH-GL'],
    ['Zug', 'CH-ZG'],
    ['Fribourg', 'CH-FR'],
    ['Solothurn', 'CH-SO'],
    ['Basel-Stadt', 'CH-BS'],
    ['Basel-Landschaft', 'CH-BL'],
    ['Schaffhausen', 'CH-SH'],
    ['Appenzell Ausserrhoden', 'CH-AR'],
    ['Appenzell Innerrhoden', 'CH-AI'],
    ['St. Gallen', 'CH-SG'],
    ['Graubünden', 'CH-GR'],
    ['Aargau', 'CH-AG'],
    ['Thurgau', 'CH-TG'],
    ['Ticino', 'CH-TI'],
    ['Vaud', 'CH-VD'],
    ['Valais', 'CH-VS'],
    ['Neuchâtel', 'CH-NE'],
    ['Geneva', 'CH-GE'],
    ['Jura', 'CH-JU']
  ],
  ES: [
    ['Whole country', 'all'],
    ['Andalusia', 'ES-AN'],
    ['Aragon', 'ES-AR'],
    ['Asturias', 'ES-AS'],
    ['Canary Islands', 'ES-CN'],
    ['Cantabria', 'ES-CB'],
    ['Castile and León', 'ES-CL'],
    ['Castilla-La Mancha', 'ES-CM'],
    ['Catalonia', 'ES-CT'],
    ['Extremadura', 'ES-EX'],
    ['Galicia', 'ES-GA'],
    ['Balearic Islands', 'ES-IB'],
    ['La Rioja', 'ES-RI'],
    ['Madrid', 'ES-MD'],
    ['Murcia', 'ES-MC'],
    ['Navarre', 'ES-NC'],
    ['Basque Country', 'ES-PV'],
    ['Valencian Community', 'ES-VC'],
    ['Ceuta', 'ES-CE'],
    ['Melilla', 'ES-ML']
  ],
  GB: [
    ['Whole country', 'all'],
    ['England', 'GB-ENG'],
    ['Scotland', 'GB-SCT'],
    ['Wales', 'GB-WLS'],
    ['Northern Ireland', 'GB-NIR']
  ],
  US: [
    ['Whole country', 'all'],
    ['Alabama', 'US-AL'],
    ['Alaska', 'US-AK'],
    ['Arizona', 'US-AZ'],
    ['Arkansas', 'US-AR'],
    ['California', 'US-CA'],
    ['Colorado', 'US-CO'],
    ['Connecticut', 'US-CT'],
    ['Delaware', 'US-DE'],
    ['Florida', 'US-FL'],
    ['Georgia', 'US-GA'],
    ['Hawaii', 'US-HI'],
    ['Idaho', 'US-ID'],
    ['Illinois', 'US-IL'],
    ['Indiana', 'US-IN'],
    ['Iowa', 'US-IA'],
    ['Kansas', 'US-KS'],
    ['Kentucky', 'US-KY'],
    ['Louisiana', 'US-LA'],
    ['Maine', 'US-ME'],
    ['Maryland', 'US-MD'],
    ['Massachusetts', 'US-MA'],
    ['Michigan', 'US-MI'],
    ['Minnesota', 'US-MN'],
    ['Mississippi', 'US-MS'],
    ['Missouri', 'US-MO'],
    ['Montana', 'US-MT'],
    ['Nebraska', 'US-NE'],
    ['Nevada', 'US-NV'],
    ['New Hampshire', 'US-NH'],
    ['New Jersey', 'US-NJ'],
    ['New Mexico', 'US-NM'],
    ['New York', 'US-NY'],
    ['North Carolina', 'US-NC'],
    ['North Dakota', 'US-ND'],
    ['Ohio', 'US-OH'],
    ['Oklahoma', 'US-OK'],
    ['Oregon', 'US-OR'],
    ['Pennsylvania', 'US-PA'],
    ['Rhode Island', 'US-RI'],
    ['South Carolina', 'US-SC'],
    ['South Dakota', 'US-SD'],
    ['Tennessee', 'US-TN'],
    ['Texas', 'US-TX'],
    ['Utah', 'US-UT'],
    ['Vermont', 'US-VT'],
    ['Virginia', 'US-VA'],
    ['Washington', 'US-WA'],
    ['West Virginia', 'US-WV'],
    ['Wisconsin', 'US-WI'],
    ['Wyoming', 'US-WY'],
    ['District of Columbia', 'US-DC']
  ],
  AU: [
    ['Whole country', 'all'],
    ['Australian Capital Territory', 'AU-ACT'],
    ['New South Wales', 'AU-NSW'],
    ['Northern Territory', 'AU-NT'],
    ['Queensland', 'AU-QLD'],
    ['South Australia', 'AU-SA'],
    ['Tasmania', 'AU-TAS'],
    ['Victoria', 'AU-VIC'],
    ['Western Australia', 'AU-WA']
  ],
  CA: [
    ['Whole country', 'all'],
    ['Alberta', 'CA-AB'],
    ['British Columbia', 'CA-BC'],
    ['Manitoba', 'CA-MB'],
    ['New Brunswick', 'CA-NB'],
    ['Newfoundland and Labrador', 'CA-NL'],
    ['Nova Scotia', 'CA-NS'],
    ['Northwest Territories', 'CA-NT'],
    ['Nunavut', 'CA-NU'],
    ['Ontario', 'CA-ON'],
    ['Prince Edward Island', 'CA-PE'],
    ['Quebec', 'CA-QC'],
    ['Saskatchewan', 'CA-SK'],
    ['Yukon', 'CA-YT']
  ],
  NZ: [
    ['Whole country', 'all'],
    ['Auckland', 'NZ-AUK'],
    ['Bay of Plenty', 'NZ-BOP'],
    ['Canterbury', 'NZ-CAN'],
    ['Chatham Islands', 'NZ-CIT'],
    ['Gisborne', 'NZ-GIS'],
    ['Hawke\'s Bay', 'NZ-HKB'],
    ['Marlborough', 'NZ-MBH'],
    ['Manawatū-Whanganui', 'NZ-MWT'],
    ['Nelson', 'NZ-NSN'],
    ['Northland', 'NZ-NTL'],
    ['Otago', 'NZ-OTA'],
    ['Southland', 'NZ-STL'],
    ['Taranaki', 'NZ-TKI'],
    ['Wellington', 'NZ-WGN'],
    ['Waikato', 'NZ-WKO'],
    ['West Coast', 'NZ-WTC']
  ],
  PT: [
    ['Whole country', 'all'],
    ['Azores', 'PT-20'],
    ['Madeira', 'PT-30']
  ],
  BA: [
    ['Whole country', 'all'],
    ['Federation of Bosnia and Herzegovina', 'BA-BIH'],
    ['Republika Srpska', 'BA-SRP']
  ],
  BQ: [
    ['Whole country', 'all'],
    ['Bonaire', 'BQ-BO'],
    ['Saba', 'BQ-SA'],
    ['Sint Eustatius', 'BQ-SE']
  ],
  IT: [
    ['Whole country', 'all'],
    ['Trentino-Alto Adige/Südtirol', 'IT-32']
  ],
  BR: [
    ['Whole country', 'all'],
    ['São Paulo', 'BR-SP']
  ],
  CL: [
    ['Whole country', 'all'],
    ['Arica y Parinacota', 'CL-AP']
  ]
};

module.exports = {
  COUNTRY_OPTIONS: COUNTRY_OPTIONS,
  REGION_OPTIONS: REGION_OPTIONS
};
