
  create table "public"."telemetry_dau" (
    "watch_key" text not null,
    "activity_date" date not null,
    "account_token_hash" text,
    "fetch_count" integer not null default 0,
    "provider" public.weather_provider,
    "radar_provider" text,
    "country_code" text,
    "watch_platform" text,
    "watch_model" text,
    "watch_language" text,
    "app_version" text,
    "build_profile" text
      );


alter table "public"."telemetry_dau" enable row level security;


  create table "public"."telemetry_errors" (
    "id" bigint generated by default as identity not null,
    "received_at" timestamp with time zone not null,
    "watch_key" text,
    "account_token_hash" text,
    "provider" public.weather_provider,
    "error" text,
    "country_code" text,
    "app_version" text,
    "build_profile" text,
    "gps_error_code" integer,
    "location_mode" text,
    "duration_ms" integer,
    "attempt" integer,
    "watch_platform" text
      );


alter table "public"."telemetry_errors" enable row level security;


  create table "public"."telemetry_watch" (
    "watch_key" text not null,
    "account_token_hash" text,
    "first_seen" timestamp with time zone not null,
    "last_seen" timestamp with time zone not null,
    "lifetime_events" integer not null default 0,
    "first_app_version" text,
    "last_app_version" text,
    "country_code" text,
    "provider" public.weather_provider,
    "radar_provider" text,
    "watch_platform" text,
    "watch_model" text,
    "watch_language" text,
    "watch_firmware" text,
    "build_profile" text,
    "settings_json" jsonb
      );


alter table "public"."telemetry_watch" enable row level security;

CREATE INDEX telemetry_dau_activity_date_idx ON public.telemetry_dau USING btree (activity_date);

CREATE UNIQUE INDEX telemetry_dau_pkey ON public.telemetry_dau USING btree (watch_key, activity_date);

CREATE UNIQUE INDEX telemetry_errors_pkey ON public.telemetry_errors USING btree (id);

CREATE INDEX telemetry_errors_provider_idx ON public.telemetry_errors USING btree (provider, received_at);

CREATE INDEX telemetry_errors_received_at_idx ON public.telemetry_errors USING btree (received_at);

CREATE INDEX telemetry_watch_first_seen_idx ON public.telemetry_watch USING btree (first_seen);

CREATE INDEX telemetry_watch_last_app_version_idx ON public.telemetry_watch USING btree (last_app_version);

CREATE INDEX telemetry_watch_last_seen_idx ON public.telemetry_watch USING btree (last_seen);

CREATE UNIQUE INDEX telemetry_watch_pkey ON public.telemetry_watch USING btree (watch_key);

alter table "public"."telemetry_dau" add constraint "telemetry_dau_pkey" PRIMARY KEY using index "telemetry_dau_pkey";

alter table "public"."telemetry_errors" add constraint "telemetry_errors_pkey" PRIMARY KEY using index "telemetry_errors_pkey";

alter table "public"."telemetry_watch" add constraint "telemetry_watch_pkey" PRIMARY KEY using index "telemetry_watch_pkey";

grant delete on table "public"."telemetry_dau" to "anon";

grant insert on table "public"."telemetry_dau" to "anon";

grant references on table "public"."telemetry_dau" to "anon";

grant select on table "public"."telemetry_dau" to "anon";

grant trigger on table "public"."telemetry_dau" to "anon";

grant truncate on table "public"."telemetry_dau" to "anon";

grant update on table "public"."telemetry_dau" to "anon";

grant delete on table "public"."telemetry_dau" to "authenticated";

grant insert on table "public"."telemetry_dau" to "authenticated";

grant references on table "public"."telemetry_dau" to "authenticated";

grant select on table "public"."telemetry_dau" to "authenticated";

grant trigger on table "public"."telemetry_dau" to "authenticated";

grant truncate on table "public"."telemetry_dau" to "authenticated";

grant update on table "public"."telemetry_dau" to "authenticated";

grant delete on table "public"."telemetry_dau" to "service_role";

grant insert on table "public"."telemetry_dau" to "service_role";

grant references on table "public"."telemetry_dau" to "service_role";

grant select on table "public"."telemetry_dau" to "service_role";

grant trigger on table "public"."telemetry_dau" to "service_role";

grant truncate on table "public"."telemetry_dau" to "service_role";

grant update on table "public"."telemetry_dau" to "service_role";

grant delete on table "public"."telemetry_errors" to "anon";

grant insert on table "public"."telemetry_errors" to "anon";

grant references on table "public"."telemetry_errors" to "anon";

grant select on table "public"."telemetry_errors" to "anon";

grant trigger on table "public"."telemetry_errors" to "anon";

grant truncate on table "public"."telemetry_errors" to "anon";

grant update on table "public"."telemetry_errors" to "anon";

grant delete on table "public"."telemetry_errors" to "authenticated";

grant insert on table "public"."telemetry_errors" to "authenticated";

grant references on table "public"."telemetry_errors" to "authenticated";

grant select on table "public"."telemetry_errors" to "authenticated";

grant trigger on table "public"."telemetry_errors" to "authenticated";

grant truncate on table "public"."telemetry_errors" to "authenticated";

grant update on table "public"."telemetry_errors" to "authenticated";

grant delete on table "public"."telemetry_errors" to "service_role";

grant insert on table "public"."telemetry_errors" to "service_role";

grant references on table "public"."telemetry_errors" to "service_role";

grant select on table "public"."telemetry_errors" to "service_role";

grant trigger on table "public"."telemetry_errors" to "service_role";

grant truncate on table "public"."telemetry_errors" to "service_role";

grant update on table "public"."telemetry_errors" to "service_role";

grant delete on table "public"."telemetry_watch" to "anon";

grant insert on table "public"."telemetry_watch" to "anon";

grant references on table "public"."telemetry_watch" to "anon";

grant select on table "public"."telemetry_watch" to "anon";

grant trigger on table "public"."telemetry_watch" to "anon";

grant truncate on table "public"."telemetry_watch" to "anon";

grant update on table "public"."telemetry_watch" to "anon";

grant delete on table "public"."telemetry_watch" to "authenticated";

grant insert on table "public"."telemetry_watch" to "authenticated";

grant references on table "public"."telemetry_watch" to "authenticated";

grant select on table "public"."telemetry_watch" to "authenticated";

grant trigger on table "public"."telemetry_watch" to "authenticated";

grant truncate on table "public"."telemetry_watch" to "authenticated";

grant update on table "public"."telemetry_watch" to "authenticated";

grant delete on table "public"."telemetry_watch" to "service_role";

grant insert on table "public"."telemetry_watch" to "service_role";

grant references on table "public"."telemetry_watch" to "service_role";

grant select on table "public"."telemetry_watch" to "service_role";

grant trigger on table "public"."telemetry_watch" to "service_role";

grant truncate on table "public"."telemetry_watch" to "service_role";

grant update on table "public"."telemetry_watch" to "service_role";


  create policy "no_api_access_telemetry_dau"
  on "public"."telemetry_dau"
  as permissive
  for all
  to anon, authenticated
using (false)
with check (false);



  create policy "no_api_access_telemetry_errors"
  on "public"."telemetry_errors"
  as permissive
  for all
  to anon, authenticated
using (false)
with check (false);



  create policy "no_api_access_telemetry_watch"
  on "public"."telemetry_watch"
  as permissive
  for all
  to anon, authenticated
using (false)
with check (false);



