
  create table "public"."news" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "target_version" text,
    "title" text not null,
    "body_md" text not null,
    "choices" jsonb
      );


alter table "public"."news" enable row level security;


  create table "public"."news_replies" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "news_id" bigint not null,
    "account_token_hash" text not null,
    "app_version" text not null,
    "message" text not null
      );


alter table "public"."news_replies" enable row level security;


  create table "public"."news_seen" (
    "account_token_hash" text not null,
    "last_seen_news_id" bigint not null default 0,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."news_seen" enable row level security;


  create table "public"."news_votes" (
    "news_id" bigint not null,
    "account_token_hash" text not null,
    "choice_index" integer not null,
    "choice_text" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."news_votes" enable row level security;

CREATE UNIQUE INDEX news_pkey ON public.news USING btree (id);

CREATE UNIQUE INDEX news_replies_pkey ON public.news_replies USING btree (id);

CREATE INDEX news_replies_rate_idx ON public.news_replies USING btree (account_token_hash, created_at);

CREATE UNIQUE INDEX news_seen_pkey ON public.news_seen USING btree (account_token_hash);

CREATE UNIQUE INDEX news_votes_pkey ON public.news_votes USING btree (news_id, account_token_hash);

CREATE INDEX news_votes_rate_idx ON public.news_votes USING btree (account_token_hash, updated_at);

alter table "public"."news" add constraint "news_pkey" PRIMARY KEY using index "news_pkey";

alter table "public"."news_replies" add constraint "news_replies_pkey" PRIMARY KEY using index "news_replies_pkey";

alter table "public"."news_seen" add constraint "news_seen_pkey" PRIMARY KEY using index "news_seen_pkey";

alter table "public"."news_votes" add constraint "news_votes_pkey" PRIMARY KEY using index "news_votes_pkey";

alter table "public"."news" add constraint "news_body_md_check" CHECK ((length(btrim(body_md)) > 0)) not valid;

alter table "public"."news" validate constraint "news_body_md_check";

alter table "public"."news" add constraint "news_choices_check" CHECK (((choices IS NULL) OR (jsonb_typeof(choices) = 'array'::text))) not valid;

alter table "public"."news" validate constraint "news_choices_check";

alter table "public"."news" add constraint "news_title_check" CHECK ((length(btrim(title)) > 0)) not valid;

alter table "public"."news" validate constraint "news_title_check";

alter table "public"."news_replies" add constraint "news_replies_message_check" CHECK (((length(btrim(message)) > 0) AND (length(message) <= 1000))) not valid;

alter table "public"."news_replies" validate constraint "news_replies_message_check";

alter table "public"."news_replies" add constraint "news_replies_news_id_fkey" FOREIGN KEY (news_id) REFERENCES public.news(id) ON DELETE CASCADE not valid;

alter table "public"."news_replies" validate constraint "news_replies_news_id_fkey";

alter table "public"."news_votes" add constraint "news_votes_choice_index_check" CHECK ((choice_index >= 0)) not valid;

alter table "public"."news_votes" validate constraint "news_votes_choice_index_check";

alter table "public"."news_votes" add constraint "news_votes_news_id_fkey" FOREIGN KEY (news_id) REFERENCES public.news(id) ON DELETE CASCADE not valid;

alter table "public"."news_votes" validate constraint "news_votes_news_id_fkey";

grant delete on table "public"."news" to "anon";

grant insert on table "public"."news" to "anon";

grant references on table "public"."news" to "anon";

grant select on table "public"."news" to "anon";

grant trigger on table "public"."news" to "anon";

grant truncate on table "public"."news" to "anon";

grant update on table "public"."news" to "anon";

grant delete on table "public"."news" to "authenticated";

grant insert on table "public"."news" to "authenticated";

grant references on table "public"."news" to "authenticated";

grant select on table "public"."news" to "authenticated";

grant trigger on table "public"."news" to "authenticated";

grant truncate on table "public"."news" to "authenticated";

grant update on table "public"."news" to "authenticated";

grant delete on table "public"."news" to "service_role";

grant insert on table "public"."news" to "service_role";

grant references on table "public"."news" to "service_role";

grant select on table "public"."news" to "service_role";

grant trigger on table "public"."news" to "service_role";

grant truncate on table "public"."news" to "service_role";

grant update on table "public"."news" to "service_role";

grant delete on table "public"."news_replies" to "anon";

grant insert on table "public"."news_replies" to "anon";

grant references on table "public"."news_replies" to "anon";

grant select on table "public"."news_replies" to "anon";

grant trigger on table "public"."news_replies" to "anon";

grant truncate on table "public"."news_replies" to "anon";

grant update on table "public"."news_replies" to "anon";

grant delete on table "public"."news_replies" to "authenticated";

grant insert on table "public"."news_replies" to "authenticated";

grant references on table "public"."news_replies" to "authenticated";

grant select on table "public"."news_replies" to "authenticated";

grant trigger on table "public"."news_replies" to "authenticated";

grant truncate on table "public"."news_replies" to "authenticated";

grant update on table "public"."news_replies" to "authenticated";

grant delete on table "public"."news_replies" to "service_role";

grant insert on table "public"."news_replies" to "service_role";

grant references on table "public"."news_replies" to "service_role";

grant select on table "public"."news_replies" to "service_role";

grant trigger on table "public"."news_replies" to "service_role";

grant truncate on table "public"."news_replies" to "service_role";

grant update on table "public"."news_replies" to "service_role";

grant delete on table "public"."news_seen" to "anon";

grant insert on table "public"."news_seen" to "anon";

grant references on table "public"."news_seen" to "anon";

grant select on table "public"."news_seen" to "anon";

grant trigger on table "public"."news_seen" to "anon";

grant truncate on table "public"."news_seen" to "anon";

grant update on table "public"."news_seen" to "anon";

grant delete on table "public"."news_seen" to "authenticated";

grant insert on table "public"."news_seen" to "authenticated";

grant references on table "public"."news_seen" to "authenticated";

grant select on table "public"."news_seen" to "authenticated";

grant trigger on table "public"."news_seen" to "authenticated";

grant truncate on table "public"."news_seen" to "authenticated";

grant update on table "public"."news_seen" to "authenticated";

grant delete on table "public"."news_seen" to "service_role";

grant insert on table "public"."news_seen" to "service_role";

grant references on table "public"."news_seen" to "service_role";

grant select on table "public"."news_seen" to "service_role";

grant trigger on table "public"."news_seen" to "service_role";

grant truncate on table "public"."news_seen" to "service_role";

grant update on table "public"."news_seen" to "service_role";

grant delete on table "public"."news_votes" to "anon";

grant insert on table "public"."news_votes" to "anon";

grant references on table "public"."news_votes" to "anon";

grant select on table "public"."news_votes" to "anon";

grant trigger on table "public"."news_votes" to "anon";

grant truncate on table "public"."news_votes" to "anon";

grant update on table "public"."news_votes" to "anon";

grant delete on table "public"."news_votes" to "authenticated";

grant insert on table "public"."news_votes" to "authenticated";

grant references on table "public"."news_votes" to "authenticated";

grant select on table "public"."news_votes" to "authenticated";

grant trigger on table "public"."news_votes" to "authenticated";

grant truncate on table "public"."news_votes" to "authenticated";

grant update on table "public"."news_votes" to "authenticated";

grant delete on table "public"."news_votes" to "service_role";

grant insert on table "public"."news_votes" to "service_role";

grant references on table "public"."news_votes" to "service_role";

grant select on table "public"."news_votes" to "service_role";

grant trigger on table "public"."news_votes" to "service_role";

grant truncate on table "public"."news_votes" to "service_role";

grant update on table "public"."news_votes" to "service_role";


  create policy "no_api_access_news"
  on "public"."news"
  as permissive
  for all
  to anon, authenticated
using (false)
with check (false);



  create policy "no_api_access_news_replies"
  on "public"."news_replies"
  as permissive
  for all
  to anon, authenticated
using (false)
with check (false);



  create policy "no_api_access_news_seen"
  on "public"."news_seen"
  as permissive
  for all
  to anon, authenticated
using (false)
with check (false);



  create policy "no_api_access_news_votes"
  on "public"."news_votes"
  as permissive
  for all
  to anon, authenticated
using (false)
with check (false);



